# we need trusty for the chrome addon
dist: trusty

# we don't need sudo, so can run in a container, which makes startup much
# quicker.
#
# unfortunately we do temporarily require sudo as a workaround for
# https://github.com/travis-ci/travis-ci/issues/8836
sudo: required

language: node_js
node_js:
    # make sure we work with a range of node versions.
    #
    # Current status of node versions: https://github.com/nodejs/LTS/
    # We don't work with node 6 because it doesn't support package-lock
    # files which we need to avoid the broken version of base-x
    - 8
    - 10
addons:
    chrome: stable
install:
    # clone the deps with depth 1: we know we will only ever need that one
    # commit.
    - npm install && scripts/fetch-develop.deps.sh --depth 1
script:
    - CHROME_BIN='/usr/bin/google-chrome-stable' npm run test
    - npm run lint
