name: Publish shared component npm package
on:
    workflow_dispatch: {}

concurrency: release
jobs:
    publish:
        name: "Publish"
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write

        steps:
            - name: ğŸ§® Checkout code
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

            - name: ğŸ”§ Set up node environment
              uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
              with:
                  cache: "yarn"
                  node-version-file: ".node-version"
                  registry-url: "https://registry.npmjs.org"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.ELEMENT_NPM_TOKEN }}

            - name: ğŸ› ï¸ Setup
              # When running `install` it also calls the `prepare` step which generates
              # a build
              run: yarn --cwd packages/shared-components install --pure-lockfile

            - name: ğŸš€ Publish to npm
              working-directory: packages/shared-components
              run: npm publish --access public --provenance
