name: Publish shared component npm package
on:
    workflow_dispatch: {}

concurrency: release
jobs:
    publish:
        name: "Publish"
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write

        steps:
            - name: ğŸ§® Checkout code
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

            - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
            - name: ğŸ”§ Set up node environment
              uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
              with:
                  cache: "pnpm"
                  node-version-file: ".node-version"
                  registry-url: "https://registry.npmjs.org"

            # Ensure npm 11.5.1 or later is installed
            - name: Update npm
              run: npm install -g npm@latest

            # Need to setup element web too as it needs the translations
            - name: ğŸ› ï¸ Setup EW
              run: pnpm install --frozen-lockfile

            - name: ğŸ› ï¸ Setup
              # When running `install` it also calls the `prepare` step which generates
              # a build
              run: pnpm --dir packages/shared-components install --frozen-lockfile

            - name: ğŸš€ Publish to npm
              working-directory: packages/shared-components
              run: npm publish --access public --provenance
