name: Move new issues into Issue triage board

on:
    issues:
        types: [opened]

permissions: {} # We use ELEMENT_BOT_TOKEN instead

jobs:
    automate-project-columns:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/add-to-project@main
              with:
                  project-url: https://github.com/orgs/element-hq/projects/120
                  github-token: ${{ secrets.ELEMENT_BOT_TOKEN }}
